// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
#include "CANTalon.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<CANTalon> RobotMap::dRIVE_SUBCANTalon1;
std::shared_ptr<CANTalon> RobotMap::dRIVE_SUBCANTalon2;
std::shared_ptr<CANTalon> RobotMap::dRIVE_SUBCANTalon3;
std::shared_ptr<CANTalon> RobotMap::dRIVE_SUBCANTalon4;
std::shared_ptr<RobotDrive> RobotMap::dRIVE_SUBROBOT_DRIVE;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    dRIVE_SUBCANTalon1.reset(new CANTalon(1));
    lw->AddActuator("DRIVE_SUB", "CAN Talon 1", dRIVE_SUBCANTalon1);
    
    dRIVE_SUBCANTalon2.reset(new CANTalon(2));
    lw->AddActuator("DRIVE_SUB", "CAN Talon 2", dRIVE_SUBCANTalon2);
    
    dRIVE_SUBCANTalon3.reset(new CANTalon(3));
    lw->AddActuator("DRIVE_SUB", "CAN Talon 3", dRIVE_SUBCANTalon3);
    
    dRIVE_SUBCANTalon4.reset(new CANTalon(4));
    lw->AddActuator("DRIVE_SUB", "CAN Talon 4", dRIVE_SUBCANTalon4);
    
    dRIVE_SUBROBOT_DRIVE.reset(new RobotDrive(dRIVE_SUBCANTalon1, dRIVE_SUBCANTalon2,
              dRIVE_SUBCANTalon3, dRIVE_SUBCANTalon4));
    
    dRIVE_SUBROBOT_DRIVE->SetSafetyEnabled(true);
        dRIVE_SUBROBOT_DRIVE->SetExpiration(0.1);
        dRIVE_SUBROBOT_DRIVE->SetSensitivity(0.5);
        dRIVE_SUBROBOT_DRIVE->SetMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
